# Generated by Django 4.2.6 on 2023-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingdata",
            name="data",
            field=models.JSONField(),
        ),
    ]
