# Generated by Django 4.2.6 on 2023-10-24 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_alter_trainingdata_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingdata",
            name="create",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
