name: Publish Conda

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install conda client
      run: |
        conda install anaconda-client conda-build
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build Package
      run: |
        make build
    - name: Upload Package
      run: |
        anaconda login --username quillcraftsman --password ${{ secrets.ANACONDA_PASSWORD }}
        anaconda upload dist/*.tar.gz
